language: go

go:
  - master

install:
  - go get -t -v github.com/google/go-querystring/query
  - go get -t -v github.com/mitchellh/mapstructure

notifications:
  email: true

os: osx

script:
  - go test -race -coverprofile=../coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)