language: go

go:
  - 1.x
  - master

install:
  - go get -t -v github.com/google/go-querystring/query
  - go get -t -v github.com/bozd4g/go-http-client/client

notifications:
  email: true

os: osx

script:
  - go test client_test.go -v