language: go

go:
  - master

install:
  - go mod install

notifications:
  email: true

os: osx

script:
  - go test -race -coverprofile=../coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)